Repository akaanuzman/digital_order_system, pull requests merged in 2023-05, with the labels that each got.

#35 UserHomeView & FoodCardDetail
  assets/images/burger.png
  assets/images/fast_food.png
  assets/images/fruit.png
  assets/images/main_dishes.png
  assets/images/salad.png
  assets/langs/app_tr.arb
  lib/products/constants/image_constants.dart
  lib/products/theme/color/app_colors.dart
  lib/views/home/food_detail_card_view.dart
  lib/views/home/user_home_view.dart
  lib/views/home/user_select_meal_type_view.dart
Labels: clean, ui_development

#36 merge changes from alperen branch
  lib/views/home/user_home_view.dart
  lib/views/home/user_select_meal_type_view.dart
Labels: synchronization

#37 restorant and user ui changes
  assets/images/burger.png
  assets/images/fast_food.png
  assets/images/fruit.png
  assets/images/main_dishes.png
  assets/images/salad.png
  assets/langs/app_tr.arb
  ios/Podfile.lock
  lib/_export_ui.dart
  lib/core/components/skeleton/skeleton_item.dart
  lib/core/components/skeleton/skeleton_list.dart
  lib/main.dart
  lib/products/components/appbar/restaurant_appbar.dart
  lib/products/components/button/custom_outlined_button.dart
  lib/products/components/row/row_icon_text.dart
  lib/products/components/row/row_icon_text_for_order_and_user_information.dart
  lib/products/components/row/special_row_button.dart
  lib/products/components/text/display_medium_text.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/constants/image_constants.dart
  lib/products/constants/string_constants.dart
  lib/products/enums/aspect_ratio_enum.dart
  lib/products/enums/platform_enum.dart
  lib/products/enums/text_sizes_enum.dart
  lib/products/models/local/onboard_model.dart
  lib/products/models/local/tabbar_model.dart
  lib/products/models/service/restaurant_model.dart
  lib/products/models/service/verison_model.dart
  lib/products/theme/app_theme.dart
  lib/products/theme/color/app_colors.dart
  lib/products/theme/text/app_texts.dart
  lib/products/utility/base/base_firebase_model.dart
  lib/products/utility/base/base_singleton.dart
  lib/products/utility/exception/firebase_custom_exception.dart
  lib/products/utility/exception/version_custom_exception.dart
  lib/products/utility/firebase/firebase_collections.dart
  lib/products/utility/managers/version_manager.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/navbar_view_model.dart
  lib/products/view_models/splash_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/profile/profile_complete_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/auth/user_selection/user_selection_view.dart
  lib/views/common/navbar/navbar_view.dart
  lib/views/common/onboard/onboard_view.dart
  lib/views/common/splash/splash_view.dart
  lib/views/home/food/restaurant_food_view.dart
  lib/views/home/food_detail_card_view.dart
  lib/views/home/order/restaurant_current_orders_view.dart
  lib/views/home/order/restaurant_orders_view.dart
  lib/views/home/order/restaurant_past_order_detail_view.dart
  lib/views/home/order/restaurant_past_orders_view.dart
  lib/views/home/user_home_view.dart
  lib/views/home/user_select_meal_type_view.dart
  lib/views/test.dart
  pubspec.lock
  pubspec.yaml
Labels: synchronization

#38 synchronization for "alperen" branch
  README.md
Labels: synchronization

#39 login and register operations and home ui development
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/core/utils/app_validators.dart
  lib/main.dart
  lib/products/components/text_field/profile_text_field.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/models/service/customer_model.dart
  lib/products/models/service/restaurant_model.dart
  lib/products/models/service/verison_model.dart
  lib/products/utility/service/auth_service.dart
  lib/products/utility/service/collections_service.dart
  lib/products/utility/service/error_handler_service.dart
  lib/products/utility/service/firestore_service.dart
  lib/products/utility/service/locale_services.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/image_view_model.dart
  lib/products/view_models/login_view_model.dart
  lib/products/view_models/navbar_view_model.dart
  lib/products/view_models/onboard_view_model.dart
  lib/products/view_models/register_view_model.dart
  lib/products/view_models/splash_view_model.dart
  lib/products/view_models/user_selection_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/profile/profile_complete_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/auth/user_selection/user_selection_view.dart
  lib/views/common/navbar/navbar_view.dart
  lib/views/home/drink/drink_operations_view.dart
  lib/views/home/food/food_operations_view.dart
  lib/views/home/kitchen/kitchen_operations_view.dart
  lib/views/home/user_home_view.dart
  lib/views/home/user_select_meal_type_view.dart
  lib/views/test.dart
  pubspec.lock
  pubspec.yaml
Labels: ui_development, backend

#40 synchronization for "alperen" branch
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/core/utils/app_validators.dart
  lib/main.dart
  lib/products/components/text_field/profile_text_field.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/models/service/customer_model.dart
  lib/products/models/service/restaurant_model.dart
  lib/products/models/service/verison_model.dart
  lib/products/utility/service/auth_service.dart
  lib/products/utility/service/collections_service.dart
  lib/products/utility/service/error_handler_service.dart
  lib/products/utility/service/firestore_service.dart
  lib/products/utility/service/locale_services.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/image_view_model.dart
  lib/products/view_models/login_view_model.dart
  lib/products/view_models/navbar_view_model.dart
  lib/products/view_models/onboard_view_model.dart
  lib/products/view_models/register_view_model.dart
  lib/products/view_models/splash_view_model.dart
  lib/products/view_models/user_selection_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/profile/profile_complete_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/auth/user_selection/user_selection_view.dart
  lib/views/common/navbar/navbar_view.dart
  lib/views/home/drink/drink_operations_view.dart
  lib/views/home/food/food_operations_view.dart
  lib/views/home/kitchen/kitchen_operations_view.dart
  lib/views/home/user_home_view.dart
  lib/views/home/user_select_meal_type_view.dart
  lib/views/test.dart
  pubspec.lock
  pubspec.yaml
Labels: synchronization

#43 login register operations and ai deployment completed
  android/app/build.gradle
  assets/ai/age_labels.txt
  assets/ai/age_model.tflite
  assets/ai/gender_labels.txt
  assets/ai/gender_model.tflite
  assets/images/ai.jpeg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/extensions/string_extension.dart
  lib/main.dart
  lib/products/components/button/custom_button.dart
  lib/products/components/container/food_reccomendation_container.dart
  lib/products/components/information_container/informantion_container.dart
  lib/products/components/radio/custom_radio_text.dart
  lib/products/components/row/food_reccomendation_personel_info.dart
  lib/products/components/row/row_icon_text.dart
  lib/products/components/text_field/profile_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/constants/image_constants.dart
  lib/products/enums/gender_enum.dart
  lib/products/models/local/restaurant_management_model.dart
  lib/products/models/service/customer_model.dart
  lib/products/theme/app_theme.dart
  lib/products/utility/base/base_firebase_model.dart
  lib/products/utility/service/collections_service.dart
  lib/products/utility/service/firestore_service.dart
  lib/products/utility/service/locale_services.dart
  lib/products/utility/service/storage_service.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/customer_view_model.dart
  lib/products/view_models/food_reccomendation_view_model.dart
  lib/products/view_models/image_view_model.dart
  lib/products/view_models/login_view_model.dart
  lib/products/view_models/register_view_model.dart
  lib/products/view_models/restaurant_view_model.dart
  lib/products/view_models/splash_view_model.dart
  lib/products/view_models/user_selection_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/profile/profile_complete_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/home/customer/customer_select_meal_type_view.dart
  lib/views/home/customer/food_detail_card_view.dart
  lib/views/home/customer/food_reccomendation_system_view.dart
  lib/views/home/customer_home_view.dart
  lib/views/home/order/restaurant_current_orders_view.dart
  lib/views/home/restraurant/drink/drink_operations_view.dart
  lib/views/home/restraurant/drink/restaurant_drink_view.dart
  lib/views/home/restraurant/food/food_operations_view.dart
  lib/views/home/restraurant/food/restaurant_food_view.dart
  lib/views/home/restraurant/kitchen/kitchen_operations_view.dart
  lib/views/home/restraurant/kitchen/restaurant_kitchen_view.dart
  lib/views/home/restraurant/order/restaurant_current_orders_view.dart
  lib/views/home/restraurant/order/restaurant_order_detail_view.dart
  lib/views/home/restraurant/order/restaurant_orders_view.dart
  lib/views/home/restraurant/order/restaurant_past_orders_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, clean, ui_development, bugFix, backend, ai

#44 synchronization for "alperen" branch
  android/app/build.gradle
  assets/ai/age_labels.txt
  assets/ai/age_model.tflite
  assets/ai/gender_labels.txt
  assets/ai/gender_model.tflite
  assets/images/ai.jpeg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/extensions/string_extension.dart
  lib/main.dart
  lib/products/components/button/custom_button.dart
  lib/products/components/container/food_reccomendation_container.dart
  lib/products/components/information_container/informantion_container.dart
  lib/products/components/radio/custom_radio_text.dart
  lib/products/components/row/food_reccomendation_personel_info.dart
  lib/products/components/row/row_icon_text.dart
  lib/products/components/text_field/profile_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/constants/image_constants.dart
  lib/products/enums/gender_enum.dart
  lib/products/models/local/restaurant_management_model.dart
  lib/products/models/service/customer_model.dart
  lib/products/theme/app_theme.dart
  lib/products/utility/base/base_firebase_model.dart
  lib/products/utility/service/collections_service.dart
  lib/products/utility/service/firestore_service.dart
  lib/products/utility/service/locale_services.dart
  lib/products/utility/service/storage_service.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/customer_view_model.dart
  lib/products/view_models/food_reccomendation_view_model.dart
  lib/products/view_models/image_view_model.dart
  lib/products/view_models/login_view_model.dart
  lib/products/view_models/register_view_model.dart
  lib/products/view_models/restaurant_view_model.dart
  lib/products/view_models/splash_view_model.dart
  lib/products/view_models/user_selection_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/profile/profile_complete_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/home/customer/customer_select_meal_type_view.dart
  lib/views/home/customer/food_detail_card_view.dart
  lib/views/home/customer/food_reccomendation_system_view.dart
  lib/views/home/customer_home_view.dart
  lib/views/home/order/restaurant_current_orders_view.dart
  lib/views/home/restraurant/drink/drink_operations_view.dart
  lib/views/home/restraurant/drink/restaurant_drink_view.dart
  lib/views/home/restraurant/food/food_operations_view.dart
  lib/views/home/restraurant/food/restaurant_food_view.dart
  lib/views/home/restraurant/kitchen/kitchen_operations_view.dart
  lib/views/home/restraurant/kitchen/restaurant_kitchen_view.dart
  lib/views/home/restraurant/order/restaurant_current_orders_view.dart
  lib/views/home/restraurant/order/restaurant_order_detail_view.dart
  lib/views/home/restraurant/order/restaurant_orders_view.dart
  lib/views/home/restraurant/order/restaurant_past_orders_view.dart
  pubspec.lock
  pubspec.yaml
Labels: synchronization

#45 synchronization for "kaan" branch
  lib/main.dart
  lib/products/components/list_view/custom_listview.dart
  lib/products/constants/app_constants.dart
  lib/products/models/local/navbar_model.dart
  lib/products/theme/app_theme.dart
  lib/products/view_models/customer_basket_view_model.dart
  lib/views/auth/register/register_view.dart
  lib/views/common/navbar/navbar_view.dart
  lib/views/home/customer/customer_favorites_view.dart
  lib/views/home/customer/food_detail_card_view.dart
  lib/views/home/customer_basket_view.dart
  lib/views/home/customer_home_view.dart
  lib/views/home/my_basket_view_page.dart
  lib/views/home/profile.dart
  lib/views/home/profile_view.dart
Labels: synchronization
