Repository akaanuzman/digital_order_system, pull requests merged in 2023-04, with the labels that each got.

#16 new text theme, theme, and buttons
  ios/Podfile.lock
  lib/core/enums/custom_button_enum.dart
  lib/core/extensions/on_board_model_extension.dart
  lib/core/theme/color/my_colors.dart
  lib/core/theme/my_theme.dart
  lib/core/theme/text/my_texts.dart
  lib/core/utils/navigator_service.dart
  lib/features/auth/onboard/view/onboard_view.dart
  lib/features/auth/onboard/viewmodel/onboard_view_model.dart
  lib/features/common/splash/view/splash_view.dart
  lib/features/common/splash/viewmodel/splash_view_model.dart
  lib/main.dart
  lib/uikit/button/custom_button.dart
  lib/uikit/button/custom_outlined_button.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, clean, ui_development

#17 Synchronization
  ios/Podfile.lock
  lib/core/enums/custom_button_enum.dart
  lib/core/extensions/on_board_model_extension.dart
  lib/core/theme/color/my_colors.dart
  lib/core/theme/my_theme.dart
  lib/core/theme/text/my_texts.dart
  lib/core/utils/navigator_service.dart
  lib/features/auth/onboard/view/onboard_view.dart
  lib/features/auth/onboard/viewmodel/onboard_view_model.dart
  lib/features/common/splash/view/splash_view.dart
  lib/features/common/splash/viewmodel/splash_view_model.dart
  lib/main.dart
  lib/uikit/button/custom_button.dart
  lib/uikit/button/custom_outlined_button.dart
  pubspec.lock
  pubspec.yaml
Labels: synchronization

#19 navbar was added.
  lib/core/constants/app_constants.dart
  lib/core/extensions/navbar_model_extension.dart
  lib/core/theme/my_theme.dart
  lib/features/common/navbar/model/navbar_model.dart
  lib/features/common/navbar/view/navbar_view.dart
  lib/features/common/navbar/viewmodel/navbar_view_model.dart
  lib/main.dart
Labels: clean, ui_development

#20 clean code changes and ui bugs fixes.
  lib/core/constants/image_constants.dart
  lib/features/auth/login/view/login_view.dart
  lib/features/auth/register/view/register_view.dart
  lib/features/auth/user_selection/view/user_selection_view.dart
  lib/uikit/special_row/special_row.dart
  lib/uikit/special_row/special_row_button.dart
  lib/uikit/text/special_text.dart
  lib/uikit/text_field/special_text_field.dart
Labels: clean, ui_development, bugFix

#22 synchronization for "kaan" branch
  lib/core/constants/image_constants.dart
  lib/features/auth/login/view/login_view.dart
  lib/features/auth/register/view/register_view.dart
  lib/features/auth/user_selection/view/user_selection_view.dart
  lib/uikit/special_row/special_row.dart
  lib/uikit/special_row/special_row_button.dart
  lib/uikit/text/special_text.dart
  lib/uikit/text_field/special_text_field.dart
Labels: synchronization

#27 firebase initialization
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/firebase_app_id_file.json
  lib/firebase_options.dart
  lib/main.dart
  lib/products/base/base_singleton.dart
  lib/products/constants/_export_constants.dart
  lib/products/initialize/application_initialize.dart
  lib/products/theme/_export_theme.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#28 synchronization for "alperen" branch
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/firebase_app_id_file.json
  lib/firebase_options.dart
  lib/main.dart
  lib/products/base/base_singleton.dart
  lib/products/constants/_export_constants.dart
  lib/products/initialize/application_initialize.dart
  lib/products/theme/_export_theme.dart
  pubspec.lock
  pubspec.yaml
Labels: synchronization

#29 new snackbars
  lib/_export_ui.dart
  lib/core/components/skeleton/skeleton_list.dart
  lib/main.dart
  lib/products/base/base_singleton.dart
  lib/products/components/alert/special_alert.dart
  lib/products/components/button/custom_button.dart
  lib/products/components/button/custom_outlined_button.dart
  lib/products/components/row/special_checkbox_text.dart
  lib/products/components/row/special_row_button.dart
  lib/products/components/text/display_medium_text.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/constants/image_constants.dart
  lib/products/initialize/application_initialize.dart
  lib/products/theme/color/app_colors.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/splash_view_model.dart
  lib/products/view_models/user_selection_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/auth/user_selection/user_selection_view.dart
  lib/views/common/onboard/onboard_view.dart
  lib/views/common/splash/splash_view.dart
Labels: ui_development

#30 synchronization for "alperen" branch
  lib/_export_ui.dart
  lib/core/components/skeleton/skeleton_list.dart
  lib/main.dart
  lib/products/base/base_singleton.dart
  lib/products/components/alert/special_alert.dart
  lib/products/components/button/custom_button.dart
  lib/products/components/button/custom_outlined_button.dart
  lib/products/components/row/special_checkbox_text.dart
  lib/products/components/row/special_row_button.dart
  lib/products/components/text/display_medium_text.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/constants/image_constants.dart
  lib/products/initialize/application_initialize.dart
  lib/products/theme/color/app_colors.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/splash_view_model.dart
  lib/products/view_models/user_selection_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/auth/user_selection/user_selection_view.dart
  lib/views/common/onboard/onboard_view.dart
  lib/views/common/splash/splash_view.dart
Labels: synchronization

#31 login and register textfield changes
  lib/products/components/row/special_checkbox_text.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/theme/app_theme.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/login_view_model.dart
  lib/products/view_models/register_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/register/register_view.dart
Labels: ui_development

#33 synchronization for "alperen" branch
  lib/products/components/row/special_checkbox_text.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/theme/app_theme.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/login_view_model.dart
  lib/products/view_models/register_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/register/register_view.dart
Labels: synchronization

#34 restaurant management ui screen
  assets/langs/app_tr.arb
  lib/core/extensions/ui_extensions.dart
  lib/main.dart
  lib/products/components/alert/special_alert.dart
  lib/products/components/appbar/restaurant_appbar.dart
  lib/products/components/button/custom_button.dart
  lib/products/components/information_container/informantion_container.dart
  lib/products/components/row/special_checkbox_text.dart
  lib/products/components/row/special_row_button.dart
  lib/products/components/text/display_medium_text.dart
  lib/products/components/text_field/profile_text_field.dart
  lib/products/components/text_field/special_text_field.dart
  lib/products/constants/app_constants.dart
  lib/products/extensions/alert_extension.dart
  lib/products/models/local/restaurant_management_model.dart
  lib/products/theme/app_theme.dart
  lib/products/theme/text/app_texts.dart
  lib/products/utils/ui_utils.dart
  lib/products/view_models/navbar_view_model.dart
  lib/views/auth/login/login_view.dart
  lib/views/auth/profile/profile_complete_view.dart
  lib/views/auth/register/register_view.dart
  lib/views/common/navbar/navbar_view.dart
  lib/views/common/splash/splash_view.dart
  lib/views/home/drink/drink_operations_view.dart
  lib/views/home/drink/restaurant_drink_view.dart
  lib/views/home/food/food_operations_view.dart
  lib/views/home/food/restaurant_food_view.dart
  lib/views/home/kitchen/kitchen_operations_view.dart
  lib/views/home/kitchen/restaurant_kitchen_view.dart
  lib/views/home/profile_create_view.dart
  lib/views/home/restaurant_home_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, clean, ui_development
